addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.7")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.1.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.20")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.16")
